Repository growth-more/gomo-client, pull requests merged in 2025-05, with the labels that each got.

#30 [GOMO-157] 프론트엔드 배포환경 경로오류 수정
  .github/workflows/cicd.yml
Labels: fix

#31 [GOMO-157] 프론트엔드 배포환경 오류 수정
  .github/workflows/cicd.yml
Labels: fix, bug

#32 [GOMO-147] 관심사 위젯
  src/components/force-directed-graph/constants.ts
  src/components/icon-button/close.tsx
  src/components/widget/constant.ts
  src/hooks/use-upload.ts
  src/pages/main/main-page.tsx
  src/views/interest/components/index.ts
  src/views/interest/components/select-interest-color-cell-none.tsx
  src/views/interest/components/select-interest-color-cell.tsx
  src/views/interest/components/select-interest-color.tsx
  src/views/interest/components/select-interest-image.tsx
  src/views/interest/components/select-interest.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s1.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s2.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s3.tsx
  src/views/interest/modals/create-interest/create-interest-modal.tsx
  src/views/interest/modals/index.ts
  src/views/interest/modals/update-interest/update-interest-custom-modal.tsx
  src/views/interest/modals/update-interest/update-interest-name-modal.tsx
  src/views/interest/modals/update-interest/update-interest-upper-modal.tsx
  src/views/interest/widgets/interest-graph/index.ts
  src/views/interest/widgets/interest-graph/interest-graph-widget-1x1.tsx
Labels: feat

#33 [GOMO-146] 관심사 페이지
  src/api/hooks/use-interest-graph.ts
  src/components/force-directed-graph/constants.ts
  src/components/modal/main-view/main-view-sidebar.tsx
  src/components/modal/main-view/main-view.tsx
  src/views/interest/components/index.ts
  src/views/interest/components/interest-graph-indicator/interest-graph-indicator-image.tsx
  src/views/interest/components/interest-graph-indicator/interest-graph-indicator-level.tsx
  src/views/interest/components/interest-graph-indicator/interest-graph-indicator-score-bar.tsx
  src/views/interest/components/interest-graph-indicator/interest-graph-indicator-tag.tsx
  src/views/interest/components/interest-graph-indicator/interest-graph-indicator.tsx
  src/views/interest/components/interest-graph-indicator/use-interest-graph-indicator-context-menu.tsx
  src/views/interest/components/select-interest-color/select-interest-color-cell-none.tsx
  src/views/interest/components/select-interest-color/select-interest-color-cell.tsx
  src/views/interest/components/select-interest-color/select-interest-color.tsx
  src/views/interest/components/select-interest-image/select-interest-image.tsx
  src/views/interest/components/select-interest/select-interest-item.tsx
  src/views/interest/components/select-interest/select-interest.tsx
  src/views/interest/dialog/interest-delete-dialog.tsx
  src/views/interest/modals/index.ts
  src/views/interest/modals/main/interest-modal-graph-section.tsx
  src/views/interest/modals/main/interest-modal.tsx
  src/views/interest/modals/update-interest/update-interest-upper-modal.tsx
  src/views/interest/widgets/interest-graph/interest-graph-widget-1x1.tsx
Labels: feat, fix

#35 [GOMO-165] 퀘스트 설정 페이지
  src/components/input/number-input.tsx
  src/views/quest/modals/main/quest-modal-setting-list.tsx
  src/views/quest/modals/main/quest-modal-setting-section.tsx
  src/views/quest/modals/main/quest-modal.tsx
Labels: feat, fix

#37 [GOMO-163] 관심사 생성 시 상위 관심사가 자동 연결되지 않던 문제 해결
  src/api/fetches/interest.ts
  src/api/hooks/api-mutate.ts
  src/api/hooks/interest/use-create-interest.ts
  src/api/types/requests/interest.ts
  src/hooks/use-enter.ts
  src/pages/interest/components/create-interest.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s1.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s2.tsx
  src/views/interest/modals/create-interest/create-interest-modal-s3.tsx
  src/views/interest/modals/create-interest/create-interest-modal.tsx
Labels: fix
