Repository growth-more/gomo-client, pull requests merged in 2025-03, with the labels that each got.

#12 [GOMO-82] 관심사 페이지 개발
  docs/changelog.md
  docs/todo.md
  package-lock.json
  package.json
  src/api/endpoints/interest.ts
  src/api/fetches/interest.ts
  src/api/fetches/member.ts
  src/api/hooks/index.ts
  src/api/hooks/use-assign-quest.ts
  src/api/hooks/use-interest-graph.ts
  src/api/hooks/use-interest.ts
  src/api/hooks/use-major-interest.ts
  src/api/hooks/use-quest-setting.ts
  src/api/types/fetches/requests/interest.ts
  src/api/types/index.ts
  src/api/types/requests/interest.ts
  src/api/types/responses/interest.ts
  src/components/editable/text/index.ts
  src/components/force-directed-graph/force-directed-graph.tsx
  src/components/force-directed-graph/index.ts
  src/components/force-directed-graph/types.ts
  src/components/window/context.ts
  src/components/window/index.ts
  src/components/window/type.ts
  src/components/window/window-view.tsx
  src/constants/window-view/index.ts
  src/constants/window-view/interest-window-view.tsx
  src/entities/interest.ts
  src/msw/data/index.ts
  src/msw/data/interest.ts
  src/msw/handlers/index.ts
  src/msw/handlers/interest.ts
  src/pages/history/history-page.tsx
  src/pages/index.ts
  src/pages/interest/components/create-interest.tsx
  src/pages/interest/components/index.ts
  src/pages/interest/components/interest-indicator.tsx
  src/pages/interest/components/score-bar.tsx
  src/pages/interest/components/select-interest-icon.tsx
  src/pages/interest/components/select-interest.tsx
  src/pages/interest/interest-page.tsx
  src/pages/main/components/control-panel.tsx
  src/pages/quest/quest-setting-page.tsx
Labels: chore, feat, refactor, docs

#13 [GOMO-81] 로그인, 회원가입 API 연결
  docs/todo.md
  src/api/axios/axios.ts
  src/api/axios/interceptors/access-token.ts
  src/api/axios/interceptors/refresh-token.ts
  src/api/endpoints/auth.ts
  src/api/endpoints/member.ts
  src/api/endpoints/quest.ts
  src/api/fetches/auth.ts
  src/api/fetches/member.ts
  src/api/hooks/use-join.ts
  src/api/types/fetches/requests/member.ts
  src/api/types/responses/auth.ts
  src/auth/guard/only-auth.tsx
  src/auth/guard/only-guest.tsx
  src/auth/hooks/use-auth.ts
  src/auth/types/token.ts
  src/hooks/index.ts
  src/hooks/use-effect-once.ts
  src/layouts/main-layout.tsx
  src/pages/join/components/join-form/email-verify-form.tsx
  src/pages/join/components/join-form/password-form.tsx
  src/pages/join/components/join-form/personal-form.tsx
  src/pages/join/join-form-page.tsx
  src/pages/join/join-page.tsx
  src/pages/join/join-success-page.tsx
  src/pages/login/login-page.tsx
  src/pages/main/main-page.tsx
  src/stores/use-auth-store.ts
  src/stores/use-token-store.ts
  vite.config.ts
Labels: feat, fix, docs

#14 [GOMO-66] 스트릭 컴포넌트 개발
  src/api/fetches/streak.ts
  src/api/hooks/index.ts
  src/api/hooks/use-streak.ts
  src/api/types/fetches/requests/streak.ts
  src/api/types/index.ts
  src/api/types/responses/streak.ts
  src/components/heatmap/calendar/calendar-cell.tsx
  src/components/heatmap/calendar/calendar-heatmap.tsx
  src/components/heatmap/calendar/constant.ts
  src/components/heatmap/calendar/context/consumer.ts
  src/components/heatmap/calendar/context/context.ts
  src/components/heatmap/calendar/context/index.ts
  src/components/heatmap/calendar/context/provider.tsx
  src/components/heatmap/calendar/hooks/index.ts
  src/components/heatmap/calendar/hooks/use-daily-cell.ts
  src/components/heatmap/calendar/hooks/use-monthly-cell.ts
  src/components/heatmap/calendar/hooks/use-weekly-cell.ts
  src/components/heatmap/calendar/index.ts
  src/components/heatmap/calendar/types.ts
  src/components/heatmap/calendar/utils/cell-color.ts
  src/components/heatmap/calendar/utils/index.ts
  src/components/heatmap/calendar/utils/month-of-week.ts
  src/components/heatmap/index.ts
  src/components/selector/index.ts
  src/components/selector/vertical-selector.tsx
  src/constants/window-view/profile-window-view.tsx
  src/entities/index.ts
  src/entities/streak.ts
  src/global.css
  src/msw/data/index.ts
  src/msw/data/streak.ts
  src/msw/handlers/index.ts
  src/msw/handlers/streak.ts
  src/pages/join/join-page.tsx
  src/pages/profile/components/daily-streak.tsx
  src/pages/profile/components/index.ts
  src/pages/profile/components/streak-date-selector.tsx
  src/pages/profile/components/streak-type-selector.tsx
  src/pages/profile/components/streak.tsx
  src/pages/profile/components/weekly-streak.tsx
  src/pages/profile/profile-page.tsx
Labels: feat, fix, refactor

#15 [GOMO-95] Editable 컴포넌트 v2 개발
  docs/todo.md
  src/api/hooks/use-streak.ts
  src/components/editable/avatar/avatar-selector-item.tsx
  src/components/editable/avatar/avatar-selector.tsx
  src/components/editable/avatar/avatar.tsx
  src/components/editable/avatar/index.ts
  src/components/editable/avatar/v1.tsx
  src/components/editable/avatar/v2.tsx
  src/components/editable/index.ts
  src/components/editable/text/index.ts
  src/components/editable/text/v0.tsx
  src/components/editable/text/v1.tsx
  src/components/editable/text/v2.tsx
  src/components/quest/quest-item-action.tsx
  src/pages/profile/profile-page.tsx
  src/stores/index.ts
  src/stores/use-editable-store.ts
Labels: feat, refactor

#17 [GOMO-104] 관심사 페이지 API 연결 및 관심사 그래프 리팩토링
  docs/todo.md
  package-lock.json
  package.json
  src/api/fetches/interest.ts
  src/api/hooks/use-interest-graph.ts
  src/api/hooks/use-interest.ts
  src/api/types/requests/interest.ts
  src/components/editable/text/v2.tsx
  src/components/force-directed-graph/constants.ts
  src/components/force-directed-graph/d3/create-edge.ts
  src/components/force-directed-graph/d3/create-glow-filter.ts
  src/components/force-directed-graph/d3/create-simulation.ts
  src/components/force-directed-graph/d3/create-vertex.ts
  src/components/force-directed-graph/d3/drag.ts
  src/components/force-directed-graph/d3/index.ts
  src/components/force-directed-graph/d3/initialize-edge-style.ts
  src/components/force-directed-graph/d3/initialize-vertex-style.ts
  src/components/force-directed-graph/d3/use-force-directed-graph-select.ts
  src/components/force-directed-graph/d3/use-force-directed-graph.ts
  src/components/force-directed-graph/force-directed-graph.tsx
  src/components/force-directed-graph/types.ts
  src/hooks/use-inner-value.ts
  src/msw/data/interest.ts
  src/pages/interest/components/create-interest.tsx
  src/pages/interest/components/interest-indicator.tsx
  src/pages/interest/interest-page.tsx
Labels: feat, fix, refactor, docs

#18 [GOMO-97] 주요관심사 기능 개발
  docs/todo.md
  src/api/hooks/use-interest.ts
  src/api/hooks/use-major-interest.ts
  src/api/types/responses/interest.ts
  src/components/fallback-image/fallback-image.tsx
  src/components/fallback-image/index.ts
  src/components/force-directed-graph/constants.ts
  src/components/interest/index.ts
  src/components/interest/interest-level-label.tsx
  src/components/interest/interest-score-bar.tsx
  src/entities/interest.ts
  src/hooks/use-boolean.ts
  src/msw/data/interest.ts
  src/msw/handlers/interest.ts
  src/pages/interest/components/index.ts
  src/pages/interest/components/interest-indicator.tsx
  src/pages/interest/components/major-icon.tsx
  src/pages/interest/interest-page.tsx
  src/pages/profile/components/header/header-section.tsx
  src/pages/profile/components/index.ts
  src/pages/profile/components/major-interest/major-interest-item.tsx
  src/pages/profile/components/major-interest/major-interest-section.tsx
  src/pages/profile/components/streak/streak-section.tsx
  src/pages/profile/profile-page.tsx
Labels: feat

#20 [GOMO-45] CI/CD 구성
  .github/workflows/cicd.yml
  .github/workflows/pr_notification.yml
Labels: feat
